### PR TITLE
internal/qmp-gen: generate implementations for events.

### PR DESCRIPTION
**Pull request by danderson**
So, for events, the current API in package qmp isn't great - it deserializes the event into map[string]interface{}, which means I have to re-serialize it so that I can json.Unmarshal out into the correct type.

If you have ideas on how to make this nicer, I'd love to hear it. The only things I can come up with involves stuffing some autogen'd types into the qmp package, and decoding the events to structs directly.

### CODE REVIEW

**Comment by mdlayher** [comment]
Seems to me that we should probably make `qmp.Event` an interface to keep things simple.

@benlemasurier , thoughts?

**Comment by benlemasurier** [comment]
@mdlayher yeah, that makes the most sense to me

**Comment by danderson** [comment]
Could you describe what you mean by making qmp.Event an interface with more words? I'm not seeing how this would make things prettier/easier, I think I'm missing something obvious.

**Comment by danderson** [comment]
Are you still interested in this? I'd like some guidance on how you'd like me to change qmp.Event, after which I can catch up this PR to intermediate changes. (Also, I have to implement a bit more stuff because the upstream spec introduced unions in event types)

**Comment by mdlayher** [comment]
Absolutely, I totally forgot to get back to this, sorry!  I'm at a conference this week but @benlemasurier ought to be able to provide some guidance.

**Pull request closed without merging**
