### PR TITLE
update for go-libvirt's changed API

### PR DESCRIPTION
**Pull request by trapgate**
Recent breaking changes to go-libvirt's API introduced contexts to the
QEMU events endpoints used by go-qemu.

This change also converts go-qemu to a module.

### CODE REVIEW

**Review by benlemasurier — APPROVED** [review]
lgtm on :green_salad:

**Comment by stgraber** [comment]
Looking forward to this, the go-libvirt change broke LXD builds :)

**Comment by trapgate** [comment]
I'll merge this as soon as Travis completes.

**Comment by stgraber** [comment]
Since you are still on the deprecated travis-ci.org you may find yourself with up to a 2 days backlog on builds. Not to mention the service going away entirely at the end of the year.

**Comment by benlemasurier** [comment]
I get us switched over for go-qemu and go-libvirt here shortly.

**Pull request merged**
