### PR TITLE
ci: set up matrix builds with different QEMU and libvirt versions for integration testing

### LINKED ISSUE #48: ci: set up matrix builds with different QEMU and libvirt versions for integration testing

### PR DESCRIPTION
**Pull request by xmudrii**
This PR fixes #48 

I just need to know which versions should be tested, as I asked in original issue. Once I get that information, I'll update PR to reflect needs.

/cc @benlemasurier @mdlayher

### CODE REVIEW

**Comment by benlemasurier** [comment]
Thank you! Now we just need some integration tests ;)

**Comment by xmudrii** [comment]
@benlemasurier yw :) 
Maybe if you elaborate it little more I can look into it, what's needed?

**Comment by benlemasurier** [comment]
@xmudrii Take a look at the [go-libvirt](https://github.com/digitalocean/go-libvirt) project for an [example](https://github.com/digitalocean/go-libvirt/blob/master/libvirt_integration_test.go). The idea is to test functionality against running QEMU instances.

**Comment by xmudrii** [comment]
@benlemasurier thanks for example. I'll give it a try, if I manage to make something, I'll push PR for review and further feedback.

**Pull request merged**
